sudo: required
dist: trusty
language: node_js
node_js: '6'
cache:
  directories:
  - node_modules

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg --add-architecture i386 ;fi

mono: latest
addons:
  apt:
    sources:
      - deadsnakes
      - sourceline: 'ppa:ubuntu-wine/ppa'
    packages:
      - mono-devel
      - wine1.8
      - ca-certificates-mono
      - rpm
      - bsdtar
      - icnsutils
      - gcc-multilib
      - g++-multilib
      - graphicsmagick
      - rpm
      - xz-utils

install: true
  
notifications:
  email: false
before_script:
- npm prune
- npm run link
- lerna bootstrap --scope '@(function-tree|cerebral|cerebral-forms|cerebral-provider-http|cerebral-provider-firebase|cerebral-provider-forms|cerebral-router|babel-*)'
- lerna bootstrap --scope @cerebral/codemods*
after_success:
- |
  git remote add auth https://cerebraljs:${GH_TOKEN}@github.com/reflog/cerebral;
  git config --global user.email "cerebraljs@gmail.com";
  git config --global user.name "Cerebral JS";
  if [[ $TRAVIS_BRANCH == 'debugger_autoupdate' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    # TODO: check changed path to decide if npm publish necessary
    npm run link;
    lerna bootstrap;
    cd debugger;
    npm run build;
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      npm run package:wl;
    fi
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      npm run package:mac;
    fi
  fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
